env:
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
globals:
  pool: readonly
parserOptions:
  ecmaVersion: 12
rules:
  no-eval: off
  semi:
    - error
    - always
  linebreak-style:
    - error
    - unix
  object-shorthand:
    - error
    - always
